// Code generated by ent, DO NOT EDIT.

package ent

import (
	"crud-go-api/libs/data-layer/entity/tags/ent/schema"
	"crud-go-api/libs/data-layer/entity/tags/ent/tagentity"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tagentityFields := schema.TagEntity{}.Fields()
	_ = tagentityFields
	// tagentityDescUUID is the schema descriptor for uuid field.
	tagentityDescUUID := tagentityFields[0].Descriptor()
	// tagentity.DefaultUUID holds the default value on creation for the uuid field.
	tagentity.DefaultUUID = tagentityDescUUID.Default.(func() uuid.UUID)
}
