// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crud-go-api/libs/data-layer/entity/tags/ent/predicate"
	"crud-go-api/libs/data-layer/entity/tags/ent/tagentity"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TagEntityQuery is the builder for querying TagEntity entities.
type TagEntityQuery struct {
	config
	ctx        *QueryContext
	order      []tagentity.OrderOption
	inters     []Interceptor
	predicates []predicate.TagEntity
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TagEntityQuery builder.
func (teq *TagEntityQuery) Where(ps ...predicate.TagEntity) *TagEntityQuery {
	teq.predicates = append(teq.predicates, ps...)
	return teq
}

// Limit the number of records to be returned by this query.
func (teq *TagEntityQuery) Limit(limit int) *TagEntityQuery {
	teq.ctx.Limit = &limit
	return teq
}

// Offset to start from.
func (teq *TagEntityQuery) Offset(offset int) *TagEntityQuery {
	teq.ctx.Offset = &offset
	return teq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (teq *TagEntityQuery) Unique(unique bool) *TagEntityQuery {
	teq.ctx.Unique = &unique
	return teq
}

// Order specifies how the records should be ordered.
func (teq *TagEntityQuery) Order(o ...tagentity.OrderOption) *TagEntityQuery {
	teq.order = append(teq.order, o...)
	return teq
}

// First returns the first TagEntity entity from the query.
// Returns a *NotFoundError when no TagEntity was found.
func (teq *TagEntityQuery) First(ctx context.Context) (*TagEntity, error) {
	nodes, err := teq.Limit(1).All(setContextOp(ctx, teq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tagentity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (teq *TagEntityQuery) FirstX(ctx context.Context) *TagEntity {
	node, err := teq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TagEntity ID from the query.
// Returns a *NotFoundError when no TagEntity ID was found.
func (teq *TagEntityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(1).IDs(setContextOp(ctx, teq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tagentity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (teq *TagEntityQuery) FirstIDX(ctx context.Context) int {
	id, err := teq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TagEntity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TagEntity entity is found.
// Returns a *NotFoundError when no TagEntity entities are found.
func (teq *TagEntityQuery) Only(ctx context.Context) (*TagEntity, error) {
	nodes, err := teq.Limit(2).All(setContextOp(ctx, teq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tagentity.Label}
	default:
		return nil, &NotSingularError{tagentity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (teq *TagEntityQuery) OnlyX(ctx context.Context) *TagEntity {
	node, err := teq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TagEntity ID in the query.
// Returns a *NotSingularError when more than one TagEntity ID is found.
// Returns a *NotFoundError when no entities are found.
func (teq *TagEntityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(2).IDs(setContextOp(ctx, teq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tagentity.Label}
	default:
		err = &NotSingularError{tagentity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (teq *TagEntityQuery) OnlyIDX(ctx context.Context) int {
	id, err := teq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TagEntities.
func (teq *TagEntityQuery) All(ctx context.Context) ([]*TagEntity, error) {
	ctx = setContextOp(ctx, teq.ctx, "All")
	if err := teq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TagEntity, *TagEntityQuery]()
	return withInterceptors[[]*TagEntity](ctx, teq, qr, teq.inters)
}

// AllX is like All, but panics if an error occurs.
func (teq *TagEntityQuery) AllX(ctx context.Context) []*TagEntity {
	nodes, err := teq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TagEntity IDs.
func (teq *TagEntityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if teq.ctx.Unique == nil && teq.path != nil {
		teq.Unique(true)
	}
	ctx = setContextOp(ctx, teq.ctx, "IDs")
	if err = teq.Select(tagentity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (teq *TagEntityQuery) IDsX(ctx context.Context) []int {
	ids, err := teq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (teq *TagEntityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, teq.ctx, "Count")
	if err := teq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, teq, querierCount[*TagEntityQuery](), teq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (teq *TagEntityQuery) CountX(ctx context.Context) int {
	count, err := teq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (teq *TagEntityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, teq.ctx, "Exist")
	switch _, err := teq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (teq *TagEntityQuery) ExistX(ctx context.Context) bool {
	exist, err := teq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TagEntityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (teq *TagEntityQuery) Clone() *TagEntityQuery {
	if teq == nil {
		return nil
	}
	return &TagEntityQuery{
		config:     teq.config,
		ctx:        teq.ctx.Clone(),
		order:      append([]tagentity.OrderOption{}, teq.order...),
		inters:     append([]Interceptor{}, teq.inters...),
		predicates: append([]predicate.TagEntity{}, teq.predicates...),
		// clone intermediate query.
		sql:  teq.sql.Clone(),
		path: teq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TagEntity.Query().
//		GroupBy(tagentity.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (teq *TagEntityQuery) GroupBy(field string, fields ...string) *TagEntityGroupBy {
	teq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TagEntityGroupBy{build: teq}
	grbuild.flds = &teq.ctx.Fields
	grbuild.label = tagentity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.TagEntity.Query().
//		Select(tagentity.FieldUUID).
//		Scan(ctx, &v)
func (teq *TagEntityQuery) Select(fields ...string) *TagEntitySelect {
	teq.ctx.Fields = append(teq.ctx.Fields, fields...)
	sbuild := &TagEntitySelect{TagEntityQuery: teq}
	sbuild.label = tagentity.Label
	sbuild.flds, sbuild.scan = &teq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TagEntitySelect configured with the given aggregations.
func (teq *TagEntityQuery) Aggregate(fns ...AggregateFunc) *TagEntitySelect {
	return teq.Select().Aggregate(fns...)
}

func (teq *TagEntityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range teq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, teq); err != nil {
				return err
			}
		}
	}
	for _, f := range teq.ctx.Fields {
		if !tagentity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if teq.path != nil {
		prev, err := teq.path(ctx)
		if err != nil {
			return err
		}
		teq.sql = prev
	}
	return nil
}

func (teq *TagEntityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TagEntity, error) {
	var (
		nodes = []*TagEntity{}
		_spec = teq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TagEntity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TagEntity{config: teq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, teq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (teq *TagEntityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := teq.querySpec()
	_spec.Node.Columns = teq.ctx.Fields
	if len(teq.ctx.Fields) > 0 {
		_spec.Unique = teq.ctx.Unique != nil && *teq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, teq.driver, _spec)
}

func (teq *TagEntityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tagentity.Table, tagentity.Columns, sqlgraph.NewFieldSpec(tagentity.FieldID, field.TypeInt))
	_spec.From = teq.sql
	if unique := teq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if teq.path != nil {
		_spec.Unique = true
	}
	if fields := teq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tagentity.FieldID)
		for i := range fields {
			if fields[i] != tagentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := teq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := teq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := teq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := teq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (teq *TagEntityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(teq.driver.Dialect())
	t1 := builder.Table(tagentity.Table)
	columns := teq.ctx.Fields
	if len(columns) == 0 {
		columns = tagentity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if teq.sql != nil {
		selector = teq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if teq.ctx.Unique != nil && *teq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range teq.predicates {
		p(selector)
	}
	for _, p := range teq.order {
		p(selector)
	}
	if offset := teq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := teq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TagEntityGroupBy is the group-by builder for TagEntity entities.
type TagEntityGroupBy struct {
	selector
	build *TagEntityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tegb *TagEntityGroupBy) Aggregate(fns ...AggregateFunc) *TagEntityGroupBy {
	tegb.fns = append(tegb.fns, fns...)
	return tegb
}

// Scan applies the selector query and scans the result into the given value.
func (tegb *TagEntityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tegb.build.ctx, "GroupBy")
	if err := tegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TagEntityQuery, *TagEntityGroupBy](ctx, tegb.build, tegb, tegb.build.inters, v)
}

func (tegb *TagEntityGroupBy) sqlScan(ctx context.Context, root *TagEntityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tegb.fns))
	for _, fn := range tegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tegb.flds)+len(tegb.fns))
		for _, f := range *tegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TagEntitySelect is the builder for selecting fields of TagEntity entities.
type TagEntitySelect struct {
	*TagEntityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tes *TagEntitySelect) Aggregate(fns ...AggregateFunc) *TagEntitySelect {
	tes.fns = append(tes.fns, fns...)
	return tes
}

// Scan applies the selector query and scans the result into the given value.
func (tes *TagEntitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tes.ctx, "Select")
	if err := tes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TagEntityQuery, *TagEntitySelect](ctx, tes.TagEntityQuery, tes, tes.inters, v)
}

func (tes *TagEntitySelect) sqlScan(ctx context.Context, root *TagEntityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tes.fns))
	for _, fn := range tes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
