// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crud-go-api/libs/data-layer/entity/tags/ent/tagentity"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TagEntityCreate is the builder for creating a TagEntity entity.
type TagEntityCreate struct {
	config
	mutation *TagEntityMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (tec *TagEntityCreate) SetUUID(u uuid.UUID) *TagEntityCreate {
	tec.mutation.SetUUID(u)
	return tec
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (tec *TagEntityCreate) SetNillableUUID(u *uuid.UUID) *TagEntityCreate {
	if u != nil {
		tec.SetUUID(*u)
	}
	return tec
}

// SetName sets the "name" field.
func (tec *TagEntityCreate) SetName(s string) *TagEntityCreate {
	tec.mutation.SetName(s)
	return tec
}

// Mutation returns the TagEntityMutation object of the builder.
func (tec *TagEntityCreate) Mutation() *TagEntityMutation {
	return tec.mutation
}

// Save creates the TagEntity in the database.
func (tec *TagEntityCreate) Save(ctx context.Context) (*TagEntity, error) {
	tec.defaults()
	return withHooks(ctx, tec.sqlSave, tec.mutation, tec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tec *TagEntityCreate) SaveX(ctx context.Context) *TagEntity {
	v, err := tec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tec *TagEntityCreate) Exec(ctx context.Context) error {
	_, err := tec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tec *TagEntityCreate) ExecX(ctx context.Context) {
	if err := tec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tec *TagEntityCreate) defaults() {
	if _, ok := tec.mutation.UUID(); !ok {
		v := tagentity.DefaultUUID()
		tec.mutation.SetUUID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tec *TagEntityCreate) check() error {
	if _, ok := tec.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "TagEntity.uuid"`)}
	}
	if _, ok := tec.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TagEntity.name"`)}
	}
	return nil
}

func (tec *TagEntityCreate) sqlSave(ctx context.Context) (*TagEntity, error) {
	if err := tec.check(); err != nil {
		return nil, err
	}
	_node, _spec := tec.createSpec()
	if err := sqlgraph.CreateNode(ctx, tec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tec.mutation.id = &_node.ID
	tec.mutation.done = true
	return _node, nil
}

func (tec *TagEntityCreate) createSpec() (*TagEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &TagEntity{config: tec.config}
		_spec = sqlgraph.NewCreateSpec(tagentity.Table, sqlgraph.NewFieldSpec(tagentity.FieldID, field.TypeInt))
	)
	if value, ok := tec.mutation.UUID(); ok {
		_spec.SetField(tagentity.FieldUUID, field.TypeUUID, value)
		_node.UUID = value
	}
	if value, ok := tec.mutation.Name(); ok {
		_spec.SetField(tagentity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// TagEntityCreateBulk is the builder for creating many TagEntity entities in bulk.
type TagEntityCreateBulk struct {
	config
	err      error
	builders []*TagEntityCreate
}

// Save creates the TagEntity entities in the database.
func (tecb *TagEntityCreateBulk) Save(ctx context.Context) ([]*TagEntity, error) {
	if tecb.err != nil {
		return nil, tecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tecb.builders))
	nodes := make([]*TagEntity, len(tecb.builders))
	mutators := make([]Mutator, len(tecb.builders))
	for i := range tecb.builders {
		func(i int, root context.Context) {
			builder := tecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TagEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tecb *TagEntityCreateBulk) SaveX(ctx context.Context) []*TagEntity {
	v, err := tecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tecb *TagEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := tecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tecb *TagEntityCreateBulk) ExecX(ctx context.Context) {
	if err := tecb.Exec(ctx); err != nil {
		panic(err)
	}
}
