// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crud-go-api/libs/data-layer/entity/tags/ent/predicate"
	"crud-go-api/libs/data-layer/entity/tags/ent/tagentity"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TagEntityDelete is the builder for deleting a TagEntity entity.
type TagEntityDelete struct {
	config
	hooks    []Hook
	mutation *TagEntityMutation
}

// Where appends a list predicates to the TagEntityDelete builder.
func (ted *TagEntityDelete) Where(ps ...predicate.TagEntity) *TagEntityDelete {
	ted.mutation.Where(ps...)
	return ted
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ted *TagEntityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ted.sqlExec, ted.mutation, ted.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ted *TagEntityDelete) ExecX(ctx context.Context) int {
	n, err := ted.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ted *TagEntityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tagentity.Table, sqlgraph.NewFieldSpec(tagentity.FieldID, field.TypeInt))
	if ps := ted.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ted.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ted.mutation.done = true
	return affected, err
}

// TagEntityDeleteOne is the builder for deleting a single TagEntity entity.
type TagEntityDeleteOne struct {
	ted *TagEntityDelete
}

// Where appends a list predicates to the TagEntityDelete builder.
func (tedo *TagEntityDeleteOne) Where(ps ...predicate.TagEntity) *TagEntityDeleteOne {
	tedo.ted.mutation.Where(ps...)
	return tedo
}

// Exec executes the deletion query.
func (tedo *TagEntityDeleteOne) Exec(ctx context.Context) error {
	n, err := tedo.ted.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tagentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tedo *TagEntityDeleteOne) ExecX(ctx context.Context) {
	if err := tedo.Exec(ctx); err != nil {
		panic(err)
	}
}
