// Code generated by ent, DO NOT EDIT.

package ent

import (
	"crud-go-api/libs/data-layer/entity/tags/ent/tagentity"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// TagEntity is the model entity for the TagEntity schema.
type TagEntity struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID uuid.UUID `json:"uuid,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TagEntity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tagentity.FieldID:
			values[i] = new(sql.NullInt64)
		case tagentity.FieldName:
			values[i] = new(sql.NullString)
		case tagentity.FieldUUID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TagEntity fields.
func (te *TagEntity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tagentity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			te.ID = int(value.Int64)
		case tagentity.FieldUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value != nil {
				te.UUID = *value
			}
		case tagentity.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				te.Name = value.String
			}
		default:
			te.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TagEntity.
// This includes values selected through modifiers, order, etc.
func (te *TagEntity) Value(name string) (ent.Value, error) {
	return te.selectValues.Get(name)
}

// Update returns a builder for updating this TagEntity.
// Note that you need to call TagEntity.Unwrap() before calling this method if this TagEntity
// was returned from a transaction, and the transaction was committed or rolled back.
func (te *TagEntity) Update() *TagEntityUpdateOne {
	return NewTagEntityClient(te.config).UpdateOne(te)
}

// Unwrap unwraps the TagEntity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (te *TagEntity) Unwrap() *TagEntity {
	_tx, ok := te.config.driver.(*txDriver)
	if !ok {
		panic("ent: TagEntity is not a transactional entity")
	}
	te.config.driver = _tx.drv
	return te
}

// String implements the fmt.Stringer.
func (te *TagEntity) String() string {
	var builder strings.Builder
	builder.WriteString("TagEntity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", te.ID))
	builder.WriteString("uuid=")
	builder.WriteString(fmt.Sprintf("%v", te.UUID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(te.Name)
	builder.WriteByte(')')
	return builder.String()
}

// TagEntities is a parsable slice of TagEntity.
type TagEntities []*TagEntity
